FROM jupyter/scipy-notebook

ADD SimpleRegressionTest.ipynb .

ENTRYPOINT start.sh jupyter nbconvert --execute --to notebook --output-dir=test --output=SimpleRegressionTest-log SimpleRegressionTest.ipynb
